PermitRootLogin prohibit-password
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
X11Forwarding no
MaxAuthTries 3
LoginGraceTime 20
AllowUsers root
AddressFamily inet
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no
PermitUserRC no
